server:
  port: 9000
spring:
  #profiles:
   # active: native
  application:
    name: configserver
  cloud:
    config: 
      server:
        git:
          uri: file://home/gmaglio/Documenti/WS_TODOS/WS_MFJG/microservice-configuration
          searchPaths: traductor-italian,traductor-spanish,client-traductor