server:
    port: 8761
spring:
    application:
    name: discovery-server    
eureka:
  instance:
    hostname: localhost
    appname: eureka-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.0.1:8761/eureka/,http://172.17.0.1:8762/eureka/